name: Long Usage

on: push

permissions:
  pages: write
  id-token: write

jobs:
  convert:
    name: Convert Markdown to Reveal.js
    runs-on: ubuntu-22.04
    steps:
      - name: Make Envs
        run: |
          echo "REPO_URL=${{ github.server_url }}/${{ github.repository }}" >> $GITHUB_ENV
          REPO_NAME=`echo ${{ github.repository }} | cut -d'/' -f2`
          echo "TALK_URL=https://${{ github.repository_owner }}.github.io/${REPO_NAME}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Make dist Directory
        run: mkdir -p dist

      - name: Clone Reveal
        run: git clone https://github.com/hakimel/reveal.js.git 'reveal.js'

      - name: Copy Reveal To Dist
        run: cp -r reveal.js dist/

      - name: Make link QR Code
        uses: snow-actions/qrcode@v1.0.0
        with:
          text: ${{ env.TALK_URL }}
          path: "static/qrcode.png"

      - name: Copy static files
        run: cp -r static dist/static

      - name: Render vars into talk.md
        run: cat talk.md | envsubst > dist/talk.md

      - name: Build our Talk
        uses: docker://pandoc/core:3.5
        with:
          args: >-
            --slide-level 2
            --standalone
            -t revealjs
            -V theme=night
            -V revealjs-url=reveal.js
            -s dist/talk.md
            -o dist/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print envs
        run: echo "Deployed To ${{ steps.deployment.outputs.page_url }}"
